# Publish packages to npmjs
name: Publish
on:
  release:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      
      # Checkout the repository.
      # Uses: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
        
      # Install node
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          scope: '@microbs.io'
          
      # Install
      - name: Install dependencies
        run: npm ci
          
      # Publish
      - name: Publish to npmjs
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
